conda_forge_output_validation: true
# see conda_build_config.yaml#/pkg_type which controls the dependencies
noarch_platforms:
- linux_64
- win_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
